name: CI

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
        include:
          - os: windows-2019
            name: windows
          - os: ubuntu-18.04
            name: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure CMake
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: Build
        working-directory: ./build
        shell: bash
        run: cmake --build . --config Release
      - name: Prepare to upload artifact
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          mkdir artifact
          if [ "$RUNNER_OS" == "Windows" ]; then
            cp ./build/bin/Release/button-to-touch-json.dll artifact/
          else
            cp ./build/bin/Release/button-to-touch-json.so artifact/
          fi
          cp license.txt button-to-touch.json artifact/
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{matrix.name}}
          path: artifact
  release:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Create .7z and .zip files
        run: |
          cd windows
          7z a vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-windows.7z button-to-touch-json.dll license.txt button-to-touch.json
          7z a vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-windows.zip button-to-touch-json.dll license.txt button-to-touch.json

          cd ../linux
          7z a vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-linux.7z button-to-touch-json.so license.txt button-to-touch.json
          7z a vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-linux.zip button-to-touch-json.so license.txt button-to-touch.json
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{steps.tag.outputs.tag}}
          body: ${{env.GIT_COMMIT_MESSAGE_BODY}}
          draft: false
          prerelease: false
      - name: Upload Windows 7z
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./windows/vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-windows.7z
          asset_name: vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-windows.7z
          asset_content_type: application/x-7z-compressed
      - name: Upload Windows zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./windows/vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-windows.zip
          asset_name: vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-windows.zip
          asset_content_type: application/zip
      - name: Upload Linux 7z
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./linux/vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-linux.7z
          asset_name: vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-linux.7z
          asset_content_type: application/x-7z-compressed
      - name: Upload Linux zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./linux/vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-linux.zip
          asset_name: vvctre-plugin-button-to-touch-json-${{steps.tag.outputs.tag}}-linux.zip
          asset_content_type: application/zip
